version: '3'

services:
  fingerprint-analysis:
    build:
      context: .
    image: fpa:latest
    container_name: fpa
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /media/nesli/storage/Datasets/Finger/FOESamples:/home/finperprint-analysis/datasets/foe
      - ../orientation-estimation/src:/home/finperprint-analysis/foe/src
      - ../orientation-estimation/experiments:/home/finperprint-analysis/foe/experiments
      - ../orientation-estimation/results:/home/finperprint-analysis/foe/results
      - /media/nesli/storage/Datasets/Finger/NIST_SD4:/home/finperprint-analysis/datasets/fc
      - ../classification/src:/home/finperprint-analysis/fc/src
      - ../classification/experiments:/home/finperprint-analysis/fc/experiments
      - ../classification/results:/home/finperprint-analysis/fc/results
      - /media/nesli/storage/Datasets/Finger/FVC_BERKAY_TOPCU:/home/finperprint-analysis/datasets/fmd
      - ../minutiae-detection/src:/home/finperprint-analysis/fmd/src
      - ../minutiae-detection/experiments:/home/finperprint-analysis/fmd/experiments
      - ../minutiae-detection/results:/home/finperprint-analysis/fmd/results
    init: true
    stdin_open: true
    tty: true

    # Overrides default command so things don't shut down after the process ends.
    # entrypoint: /usr/local/share/docker-init.sh
    # command: sleep infinity 

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

